import React from 'react'
import {useLoaderData} from 'react-router-dom'
const SingleBook = () => {

const {_id,bookTitle,imageURL} = useLoaderData();

  return (
    <div className='mt-28 px-4 lg:px-24'>
    <h2>
      {bookTitle}
         <img src={imageURL} alt="" className='h-100'/>
    </h2>
    </div>
  )
}

export default SingleBook

//his file seems to be the component responsible for displaying details of a single book.
//It uses useLoaderData() to access the data fetched by the loader function defined in the router.
//It extracts _id, bookTitle, and imageURL from the loaded data (probably fetched from the backend) using useLoaderData().
//The JSX within this file is rendering the book details, presumably retrieved from the backend 


//------> bookcard.jsx ---> router.jsx---> singlebook.jsx how does the all work 

//When a user clicks a book card generated by BookCard.jsx, it triggers the <Link> component to navigate to /book/:id, passing the book's _id in the URL.
//React Router's router.jsx intercepts this route and loads the SingleBook component using the provided loader function.
//The loader function fetches data from http://localhost:5000/book/:id, where :id is the specific book's ID.
//SingleBook.jsx then displays the book's details using the fetched data, such as bookTitle and imageURL.
//In summary, these files work together to create a dynamic book browsing experience where users can view detailed information about a specific book by navigating through the React Router and fetching data from the backend API based on the book's ID